fix(Shosetsu): NoClassDefFoundError `okhttp3.internal.Util`
Shosetsu's kotlin-lib relies on some internal okhttp functions removed in okhttp 5.x.
Including it should provide more descriptive errors for `HTTPException`s (like 404)